title: My Blog
author: Daniel Valdez Montalvan
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog! here you will find awesome content from the web development world:
  tutorials, JavaScript Projects, React JS Projects, CSS3, Responsive Web Design,
  the latest from programming languages and more!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
